### ISSUE TITLE
Unable to send notification to FIFO SNS topic

### ISSUE THREAD

**Issue by dianepanagiotopoulos** [awspring/spring-cloud-aws#1046]
**Type**: Bug

**Component**:
SNS

**Describe the bug**
After upgrading to Spring Cloud 3.1.0, I am unable to send notifications to my local FIFO SNS topic.

The root AWS error message is: 
```
Caused by: software.amazon.awssdk.services.sns.model.InvalidParameterException: Invalid parameter: The topic should either have ContentBasedDeduplication enabled or MessageDeduplicationId provided explicitly (Service: Sns, Status Code: 400, Request ID: 0861e15c-f77f-4ff4-b1da-c06f77146332)
```
with a stacktrace of:
```
(...)
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:149)
	at org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:125)
	at io.awspring.cloud.sns.core.SnsTemplate.doSend(SnsTemplate.java:78)
	at io.awspring.cloud.sns.core.SnsTemplate.doSend(SnsTemplate.java:45)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:151)
	at io.awspring.cloud.sns.core.SnsTemplate.convertAndSend(SnsTemplate.java:106)
	at io.awspring.cloud.sns.core.SnsTemplate.convertAndSend(SnsTemplate.java:94)
	at io.awspring.cloud.sns.core.SnsTemplate.sendNotification(SnsTemplate.java:136)
```

**Sample**
Attributes on my topic:
```
awslocal sns get-topic-attributes --topic-arn arn:aws:sns:us-east-1:000000000000:my-topic.fifo
{
    "Attributes": {
        "Owner": "000000000000",
        "Policy": "{\"Version\":\"2008-10-17\",\"Id\":\"__default_policy_ID\",\"Statement\":[{\"Effect\":\"Allow\",\"Sid\":\"__default_statement_ID\",\"Principal\":{\"AWS\":\"*\"},\"Action\":[\"SNS:GetTopicAttributes\",\"SNS:SetTopicAttributes\",\"SNS:AddPermission\",\"SNS:RemovePermission\",\"SNS:DeleteTopic\",\"SNS:Subscribe\",\"SNS:ListSubscriptionsByTopic\",\"SNS:Publish\",\"SNS:Receive\"],\"Resource\":\"arn:aws:sns:us-east-1:000000000000:work-topic-osr.fifo\",\"Condition\":{\"StringEquals\":{\"AWS:SourceOwner\":\"000000000000\"}}}]}",
        "TopicArn": "arn:aws:sns:us-east-1:000000000000:work-topic-osr.fifo",
        "DisplayName": "",
        "SubscriptionsPending": "0",
        "SubscriptionsConfirmed": "0",
        "SubscriptionsDeleted": "0",
        "DeliveryPolicy": "",
        "EffectiveDeliveryPolicy": "{\"defaultHealthyRetryPolicy\": {\"numNoDelayRetries\": 0, \"numMinDelayRetries\": 0, \"minDelayTarget\": 20, \"maxDelayTarget\": 20, \"numMaxDelayRetries\": 0, \"numRetries\": 3, \"backoffFunction\": \"linear\"}, \"sicklyRetryPolicy\": null, \"throttlePolicy\": null, \"guaranteed\": false}",
        "FifoTopic": "true",
        "ContentBasedDeduplication": "true"
    }
}
```

```java
        SnsNotification<String> notification = SnsNotification.builder(json)
                .groupId(businessKey)
                .headers(Map.of("Command", commandName))
                .build();

        snsOperations.sendNotification(topicName, notification);
```

If I log the json blob I am trying to publish, and send the notification via command line, the operation is successful:

```awslocal sns publish --message "<my json>" --topic-arn arn:aws:sns:us-east-1:000000000000:my-topic.fifo --message-group-id businessKey```

**Comment by dianepanagiotopoulos** [comment]
I'm going to retract this bug - it was entirely an issue on my side. The region that was set in my `application.properties` file was incorrect, so the automatic topic creation ended up creating a topic that did not have ContentBasedDeduplication turned on. When I set the region correctly, the messages publish as expected.
