### ISSUE TITLE
@SqsListener => unable to load credentials from aws credentials file

### ISSUE THREAD

**Issue by peeteko** [awspring/spring-cloud-aws#1052]
**Type**: Bug

**Component**:
SQS (io.awspring.cloud 3.1.0)

**Describe the bug**
I have a aws credentials and config file under
C:\Users\<username>\.aws
on my local machine

Content credentials
`[default]
role_arn=arn:aws:iam::086243371668:role/iar-DevOps-Unicorns-iSendParcel
source_profile=localdev

[localdev]
aws_access_key_id=<my generated access key id>
aws_secret_access_key=<my generated secret access key>
aws_session_token=<my generated session token>
aws_expiration=2024-02-15T19:37:00.000Z`

I generate this via
aws-azure-login --configure --profile localdev
Configuring profile 'localdev'
? Azure Tenant ID: <my tenant id>
? Azure App ID URI: https://signin.aws.amazon.com/saml
? Default Username: <my user name>
? Stay logged in: skip authentication while refreshing aws credentials (true|false) true
? Default Role ARN (if multiple): arn:aws:iam::086243371668:role/iar-DevOps-Unicorns-iSendParcel
? Default Session Duration Hours (up to 12): 12
Profile saved.

aws-azure-login --no-sandbox --mode gui --profile localdev

I am able to access the queue, send messages to the queue and receive on the queue via aws-cli on my local machine
aws sqs get-queue-url --queue-name sqs-parcels-dv2-euwe01-epf-status-update-02
aws sqs send-message --message-body testmessage --queue-url https://sqs.eu-west-1.amazonaws.com/086243371668/sqs-parcels-dv2-euwe01-epf-stat
aws sqs receive-message --queue-url https://sqs.eu-west-1.amazonaws.com/086243371668/sqs-parcels-dv2-euwe01-epf-status-

But when using @SqsListener annotation in spring boot application 3.1.0 the application is not starting up

Stacktrace
_Caused by: io.awspring.cloud.sqs.QueueAttributesResolvingException: Error resolving attributes for queue sqs-parcels-dv2-euwe01-epf-status-update-02 with strategy CREATE and queueAttributesNames []
	at io.awspring.cloud.sqs.QueueAttributesResolver.wrapException(QueueAttributesResolver.java:90) ~[spring-cloud-aws-sqs-3.1.0.jar:3.1.0]
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1008) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2396) ~[na:na]
	at io.awspring.cloud.sqs.CompletableFutures.exceptionallyCompose(CompletableFutures.java:57) ~[spring-cloud-aws-sqs-3.1.0.jar:3.1.0]
	... 11 common frames omitted
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[{default=Profile(name=default, properties=[output, source_profile, region, role_arn]), dynamodb_test=Profile(name=dynamodb_test, properties=[aws_access_key_id, aws_secret_access_key]), SML-NP=Profile(name=SML-NP, properties=[azure_default_username, azure_default_duration_hours, azure_default_remember_me, azure_app_id_uri, azure_default_role_arn, azure_tenant_id]), KOENLOCAL=Profile(name=KOENLOCAL, properties=[output, aws_expiration, region, aws_access_key_id, aws_session_token, aws_secret_access_key])}, {}])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(profilesAndSectionsMap=[{default=Profile(name=default, properties=[output, source_profile, region, role_arn]), dynamodb_test=Profile(name=dynamodb_test, properties=[aws_access_key_id, aws_secret_access_key]), SML-NP=Profile(name=SML-NP, properties=[azure_default_username, azure_default_duration_hours, azure_default_remember_me, azure_app_id_uri, azure_default_role_arn, azure_tenant_id]), KOENLOCAL=Profile(name=KOENLOCAL, properties=[output, aws_expiration, region, aws_access_key_id, aws_session_token, aws_secret_access_key])}, {}])): To use assumed roles in the 'default' profile, the 'sts' service module must be on the class path., ContainerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.]
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[sdk-core-2.21.12.jar:na]
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:130) ~[auth-2.21.12.jar:na]
	at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45) ~[auth-2.21.12.jar:na]
	at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:128) ~[auth-2.21.12.jar:na]
	at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54) ~[auth-2.21.12.jar:na]
	at software.amazon.awssdk.identity.spi.IdentityProvider.resolveIdentity(IdentityProvider.java:60) ~[identity-spi-2.21.12.jar:na]
	at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.lambda$resolveCredentials$2(AwsCredentialsAuthorizationStrategy.java:112) ~[aws-core-2.21.12.jar:na]
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:56) ~[sdk-core-2.21.12.jar:na]
	at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.resolveCredentials(AwsCredentialsAuthorizationStrategy.java:112) ~[aws-core-2.21.12.jar:na]
	at software.amazon.awssdk.awscore.internal.authcontext.AwsCredentialsAuthorizationStrategy.addCredentialsToExecutionAttributes(AwsCredentialsAuthorizationStrategy.java:85) ~[aws-core-2.21.12.jar:na]
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:137) ~[aws-core-2.21.12.jar:na]
	at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsAsyncClientHandler.java:63) ~[aws-core-2.21.12.jar:na]
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.lambda$execute$1(BaseAsyncClientHandler.java:75) ~[sdk-core-2.21.12.jar:na]
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.measureApiCallSuccess(BaseAsyncClientHandler.java:294) ~[sdk-core-2.21.12.jar:na]
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:73) ~[sdk-core-2.21.12.jar:na]
	at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:49) ~[aws-core-2.21.12.jar:na]
	at software.amazon.awssdk.services.sqs.DefaultSqsAsyncClient.getQueueUrl(DefaultSqsAsyncClient.java:998) ~[sqs-2.21.12.jar:na]
	at io.awspring.cloud.sqs.QueueAttributesResolver.doResolveQueueUrl(QueueAttributesResolver.java:110) ~[spring-cloud-aws-sqs-3.1.0.jar:3.1.0]
	at io.awspring.cloud.sqs.QueueAttributesResolver.resolveQueueUrl(QueueAttributesResolver.java:96) ~[spring-cloud-aws-sqs-3.1.0.jar:3.1.0]
	... 11 common frames omitted_

**Sample**
I have created sample application
https://github.com/peeteko/sqslistener

**Comment by peeteko** [comment]
I have found solution for this problem 
You have to add the exact dependencies  software.amazon.awssdk => sts 2.21.12 and spring-cloud-aws-autoconfigure.
Only then the listening works
I have committed solution into my https://github.com/peeteko/sqslistener
<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.awspring.cloud</groupId>
			
			<artifactId>spring-cloud-aws-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-aws-autoconfigure</artifactId>
		</dependency>
		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-aws-starter-sqs</artifactId>
		</dependency>
		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-aws-starter-sns</artifactId>
		</dependency>

		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>sts</artifactId>
			<version>2.21.12</version>
		</dependency>

	</dependencies>
	<dependencyManagement>
		<dependencies>

			<dependency>
				<groupId>io.awspring.cloud</groupId>
				<artifactId>spring-cloud-aws-dependencies</artifactId>
				<version>3.1.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

**Comment by peeteko** [comment]
Issue can be closed.
