### ISSUE TITLE
Caused by: io.awspring.cloud.sqs.QueueAttributesResolvingException: Error resolving attributes for queue [QUEUE_NAME] with strategy CREATE and queueAttributesNames []

### ISSUE THREAD

**Issue by nilesh-chordia** [awspring/spring-cloud-aws#1186]
**Type**: Bug

**Component**:
 "SQS"

**Describe the bug**
During migration from spring boot 2 to spring boot 3 facing SQS issue

**Sample**
org.springframework.context.ApplicationContextException: Failed to start bean 'io.awspring.cloud.messaging.internalEndpointRegistryBeanName'
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:186)
at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:363)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:160)
at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:128)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:968)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:618)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
at com.nilesh.central.Main.main(Main.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.util.concurrent.CompletionException: io.awspring.cloud.sqs.QueueAttributesResolvingException: Error resolving attributes for queue QUEUE_NAME with strategy CREATE and queueAttributesNames []

 implementation group: 'io.awspring.cloud', name: 'spring-cloud-aws-starter-sqs', version: '3.1.1'
 implementation group: 'io.awspring.cloud', name: 'spring-cloud-aws-starter-sns', version: '3.1.1'
 implementation group: 'io.awspring.cloud', name: 'spring-cloud-starter-aws-messaging', version: '2.4.4'

**Comment by tomazfernandes** [comment]
Hi @nilesh-chordia, this is usually a connectivity issue. Can you provide the full stack trace? Thanks.

**Comment by nilesh-chordia** [comment]
@tomazfernandes, Issue is resolved, problem is with localstack older version. With newer version, it is working

**Comment by maciejwalkowiak** [comment]
Thanks for an update @nilesh-chordia. Closing

**Comment by juancresc** [comment]
in case anyone else has this issue, i was missing `sqs:GetQueueUrl` permission
