### ISSUE TITLE
Caused by: java.util.concurrent.CompletionException: io.awspring.cloud.sqs.QueueAttributesResolvingException: Error resolving attributes for queue <queue_name>.fifo with strategy CREATE and queueAttributesNames [] 

### ISSUE THREAD

**Issue by ohadab** [awspring/spring-cloud-aws#1283]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
using package io.awspring.cloud:spring-cloud-aws-sqs:3.2.1
and using @SqsListener(value = "queue-messages.fifo")

i'm getting exception: 
Caused by: java.util.concurrent.CompletionException: io.awspring.cloud.sqs.QueueAttributesResolvingException: Error resolving attributes for queue queue-messages.fifo with strategy CREATE and queueAttributesNames []
.....
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:67)
	.....
	Caused by: software.amazon.awssdk.services.sqs.model.SqsException: The action CreateQueue is not valid for this endpoint. (Service: Sqs, Status Code: 400, Request ID: <req_id>
	)
**Sample**
@SqsListener(queueNames = {"queue-messages.fifo"})
    public void handleMessage(QueueMessageEvent event) {

**Comment by ohadab** [comment]
I Tought i did give a good code sample. but i'll explain again

To isolate the issue, I created a minimal reproducible example using version 3.2.1 of io.awspring.cloud:spring-cloud-aws-sqs. 
Despite ensuring proper IAM permissions and confirming the existence of the FIFO queue (example-queue.fifo) in the correct region, the error persists when attempting to use the @SqsListener.

Here’s the reduced code sample that reproduces the issue:
pom.xml:
`<dependency>
    <groupId>io.awspring.cloud</groupId>
    <artifactId>spring-cloud-aws-sqs</artifactId>
    <version>3.2.1</version>
</dependency>`

listener class:
`import io.awspring.cloud.sqs.annotation.SqsListener;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

@Service
@Slf4j
public class ExampleSqsListener {

    @SqsListener(value = "example-queue.fifo" "example-queue.fifo", acknowledgementMode = "ALWAYS")
    public void handleMessage(String message) {
        log.info("Received message: {}", message);
    }
}`

error i got:
`Caused by: java.util.concurrent.CompletionException: io.awspring.cloud.sqs.QueueAttributesResolvingException:
Error resolving attributes for queue example-queue.fifo with strategy CREATE and queueAttributesNames []
...
Caused by: software.amazon.awssdk.services.sqs.model.SqsException: 
The action CreateQueue is not valid for this endpoint.`

The @SqsListener should connect to the specified FIFO queue (example-queue.fifo) and process messages without attempting to recreate the queue.

**note:** I noticed that when putting full SQS url in the @SqsListener(value = "https://sqs.eu-north-1.amazonaws.com/<account-id>/example-queue.fifo") it does connect successfully to queue and does not try to create queue

**Comment by tomazfernandes** [comment]
Hi @ohadab.

The only condition the framework tries to create the queue is if it gets a `QueueDoesNotExistException` when trying to resolve the queue name.

So, for some reason, it's not finding the queue in your setup.

If you could provide a minimal sample that reproduces the issue we could take a look at it.

You can also add a breakpoint in the `QueueAttributesResolver` class to try to figure out why it's not finding the queue:

https://github.com/awspring/spring-cloud-aws/blob/425b6c857ffa2ee6446f133ae07c34d270d6e569/spring-cloud-aws-sqs/src/main/java/io/awspring/cloud/sqs/QueueAttributesResolver.java#L107-L127

Let me know if that works for you, thanks.

**Comment by tomazfernandes** [comment]
Closing due to lack of feedback, we can reopen if necessary.

**Comment by juancresc** [comment]
in case anyone else has this issue, i was missing `sqs:GetQueueUrl` permission
