### ISSUE TITLE
ForcePathStyle has been configured on both S3Configuration and the client/global level

### ISSUE THREAD

**Issue by wangyue82lf** [awspring/spring-cloud-aws#1292]
**Type**: Bug

**Component**:
S3

**Describe the bug**
Using io.awspring.cloud version 3.2.1
Using dependencies: spring-cloud-aws-starter and spring-cloud-aws-starter-s3.
Also using software.amazon.awssdk:apache-client:2.25.70 to customize AWSClient.

**Sample**
S3 pathStyle can't configure by auto-configured.

Plese reference to demo from the attachement.
[demo.zip](https://github.com/user-attachments/files/18120149/demo.zip)

**Comment by maciejwalkowiak** [comment]
The problem seems to be not with Spring Cloud AWS but with AWS SDK itself or it is by design.

In your code you inject `S3ClientBuilder` and call `build()` on it. Autoconfiguration already builds S3 client using the same builder, so it this is the second time to `build()` method call on the same builder. And it just throws excpetion like this:

```
java.lang.IllegalStateException: ForcePathStyle has been configured on both S3Configuration and the client/global level. Please limit ForcePathStyle configuration to one location.

	at software.amazon.awssdk.utils.Validate.validState(Validate.java:423)
	at software.amazon.awssdk.services.s3.DefaultS3BaseClientBuilder.finalizeServiceConfiguration(DefaultS3BaseClientBuilder.java:142)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:169)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:198)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:37)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:26)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:165)
```

You can reproduce it easily with testing pure builder:

```
class S3ClientBuilderTest {

    @Test
    void foo() {
        S3ClientBuilder s3ClientBuilder = S3Client.builder()
                .region(Region.AF_SOUTH_1)
                .serviceConfiguration(c -> c.pathStyleAccessEnabled(true));
        s3ClientBuilder.build();
        s3ClientBuilder.build();
    }
}
```

In your specific sample I think you can just inject `S3Client` instead of builder. Let me know if it helps

**Comment by wangyue82lf** [comment]
Thanks for your help
