### ISSUE TITLE
No primary or single public constructor found for NotificationStatus

### ISSUE THREAD

**Issue by eduan-envel** [awspring/spring-cloud-aws#141]
**Type**: Bug

**Component**: SNS

**Describe the bug**
Boot: 2.4.6
Cloud: 2020.0.2
awspring: 2.3.1
Using webflux and Kotlin.

When adding a subscription on SNS, I get this error:

```
java.lang.IllegalStateException: No primary or single public constructor found for interface io.awspring.cloud.messaging.endpoint.NotificationStatus - and no default constructor found either
	at org.springframework.beans.BeanUtils.getResolvableConstructor(BeanUtils.java:250) ~[spring-beans-5.3.7.jar:5.3.7]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/notifications" [ExceptionHandlingWebHandler]
Stack trace:
		at org.springframework.beans.BeanUtils.getResolvableConstructor(BeanUtils.java:250) ~[spring-beans-5.3.7.jar:5.3.7]
```

**Sample**
```
@Controller
@RequestMapping("/notifications")
class NotificationTestController {

    val logger: Logger = LoggerFactory.getLogger(this.javaClass)

    @NotificationMessageMapping
    fun receiveNotification(@NotificationMessage message: String, @NotificationSubject subject: String) {
        logger.info("Received message: {}, having subject: {}", message, subject)
    }

    @NotificationUnsubscribeConfirmationMapping
    fun confirmSubscriptionMessage(notificationStatus: NotificationStatus) {
        logger.info("Unsubscribed from Topic")
        notificationStatus.confirmSubscription()
    }

    @NotificationSubscriptionMapping
    fun confirmUnsubscribeMessage(notificationStatus: NotificationStatus) {
        logger.info("Subscribed to Topic")
        notificationStatus.confirmSubscription()
    }
}
```

**Comment by maciejwalkowiak** [comment]
Support for Webflux or Reactive APIs is planned to be added for 3.0. Currently if you want to use SNS integration, you must use Spring MVC or craft Webflux integration yourself (then maybe better to do it with AWS SDK v2).
