### ISSUE TITLE
Multiple aws-secretmanager configs registers AWSSecretsManagerClient twice

### ISSUE THREAD

**Issue by jakubgruber** [awspring/spring-cloud-aws#145]
**Type**: Bug

**Component**:
Secrets Manager

**Describe the bug**
Application tries to register `AWSSecretsManagerClient` twice when multiple configs are registered in `spring.config.import` property.

Version: 2.3.0

**Sample**

Register two AWS Secrets Manager configs in `spring.config.import`.

```yaml
spring:
  config:
    import: aws-secretsmanager:/secret/app/postgres,aws-secretsmanager:/secret/app/rabbit
```

Application stack trace:

```

java.lang.IllegalStateException: Could not register object [com.amazonaws.services.secretsmanager.AWSSecretsManagerClient@3b1dc579] under bean name 'configDataAWSSecretsManager': there is already object [com.amazonaws.services.secretsmanager.AWSSecretsManagerClient@3b1dc579] bound
--
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.registerSingleton(DefaultSingletonBeanRegistry.java:124)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerSingleton(DefaultListableBeanFactory.java:1138)
at io.awspring.cloud.autoconfigure.secretsmanager.AwsSecretsManagerConfigDataLocationResolver.lambda$registerAndPromoteBean$1(AwsSecretsManagerConfigDataLocationResolver.java:113)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
at org.springframework.boot.DefaultBootstrapContext.close(DefaultBootstrapContext.java:133)
at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:392)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
at com.paymorrow.hello.HelloApplicationKt.main(HelloApplication.kt:13)


```

**Comment by jakubgruber** [comment]
The configuration was incorrect and "protocol" needs to be defined just once. 

```
spring:
  config:
    import: aws-secretsmanager:/secret/app/postgres;/secret/app/rabbit
```

Multiple AWS SecretsManager sources:

- define `aws-secretsmanager:` once
- secrets starting by `/secret/` separate by semicolon

Maybe it would be nice to highlight possibility of multiple secrets in the documentation.

**Comment by MatejNedic** [comment]
Hey @jakubgruber,
sorry for the late response, yes secrets should be split with ";".
Are you interested maybe in reflecting docs and making PR with change?

**Comment by jakubgruber** [comment]
> Are you interested maybe in reflecting docs and making PR with change?

I noticed it is mentioned it the docs, so it's my bad :))

https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC1/reference/html/index.html#integrating-your-spring-cloud-application-with-the-aws-secrets-manager
