### ISSUE TITLE
Slow integration tests due to ContextRegionProviderAutoConfiguration

### ISSUE THREAD

**Issue by joshiste** [awspring/spring-cloud-aws#155]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
Integration tests (that spin up Spring Contexts, but don't access AWS) are taking much longer than necessary because the ContextRegionProviderAutoConfiguration is always active and tries to read the instance metadata.
as you can see from the logs ~4 seconds are lost:
```
021-06-28T13:19:23.5346934Z 2021-06-28 13:19:23.533 []  INFO 2165 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [META-INF/resources/index.html]
2021-06-28T13:19:27.4789179Z 2021-06-28 13:19:27.465 [test]  WARN 2163 --- [           main] com.amazonaws.util.EC2MetadataUtils      : Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). The requested metadata is not found at http://169.254.169.254/latest/dynamic/instance-identity/document
2021-06-28T13:19:27.4791533Z 
2021-06-28T13:19:27.4793582Z com.amazonaws.SdkClientException: The requested metadata is not found at http://169.254.169.254/latest/dynamic/instance-identity/document
2021-06-28T13:19:27.4796261Z 	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:89)
2021-06-28T13:19:27.4799679Z 	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
2021-06-28T13:19:27.4803711Z 	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
2021-06-28T13:19:27.4807687Z 	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
2021-06-28T13:19:27.4810224Z 	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:403)
2021-06-28T13:19:27.4812415Z 	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:372)
2021-06-28T13:19:27.4833870Z 	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:368)
2021-06-28T13:19:27.4836560Z 	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:283)
2021-06-28T13:19:27.4841575Z 	at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
2021-06-28T13:19:27.4845498Z 	at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
2021-06-28T13:19:27.4848755Z 	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
2021-06-28T13:19:27.4852725Z 	at io.awspring.cloud.core.region.DefaultAwsRegionProviderChainDelegate.getRegion(DefaultAwsRegionProviderChainDelegate.java:37)
2021-06-28T13:19:27.4860691Z 	at io.awspring.cloud.core.config.AmazonWebserviceClientFactoryBean.createInstance(AmazonWebserviceClientFactoryBean.java:122)
2021-06-28T13:19:27.4865567Z 	at io.awspring.cloud.core.config.AmazonWebserviceClientFactoryBean.createInstance(AmazonWebserviceClientFactoryBean.java:51)
```

**Describe the solution you'd like**
A property to disable the auto configurations for `io.awspring.cloud.autoconfigure.context.*` 

**Describe alternatives you've considered**
Currently we use `@EnableAutoconfiguration(exclude=...)`

**Comment by maciejwalkowiak** [comment]
Currently in addition to `@EnableAutoConfiguration(exclude=...)` the options are:

1. Exclude auto-configuration through a properties file:

```yml
spring.autoconfigure.exclude: io.awspring.cloud.autoconfigure.context.ContextRegionProviderAutoConfiguration
```

2. Set static region 

```yml
cloud.aws.region.static: eu-west-1
```

I am thinking how typical use case is it, that there is Spring Cloud AWS on the classpath but region is not resolvable or not set statically.

**Comment by maciejwalkowiak** [comment]
Action point: verify if this is still the case in 3.0

**Comment by maciejwalkowiak** [comment]
It is still the case as this is the default behaviour of region provider chain. But since it is a core part of the framework, I don't see why would there be a property to disable region or credentials autoconfiguration. In 3.0, you can also provide your custom `AwsRegionProvider` bean for tests. I think it is such an unusual use case that we should not expose a property for it.
