### ISSUE TITLE
java.lang.StackOverflowError - spring-cloud-starter-aws-secrets-manager-config : 2.4.1

### ISSUE THREAD

**Issue by DineshNO** [awspring/spring-cloud-aws#382]
Application is going into inifinte loop upon execution.

I am trying a fetch secret with spring-cloud-starter-aws-secrets-manager-config dependency.

I am setting the AWS_ROLE_ARN=arn:aws:iam::xaxsaxsadsa:role/databricks_nss

```xml 
 <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
            <version>${spring.cloud.secrets.manager.config.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>aws-java-sdk-core</artifactId>
                    <groupId>com.amazonaws</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
            <version>1.12.215</version>
        </dependency>
```

```
java.lang.StackOverflowError
	at java.util.LinkedList$ListItr.<init>(LinkedList.java:879)
	at java.util.LinkedList.listIterator(LinkedList.java:868)
	at java.util.AbstractList.listIterator(AbstractList.java:299)
	at java.util.AbstractSequentialList.iterator(AbstractSequentialList.java:239)
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:115)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1266)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:842)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:792)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1684)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1651)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1640)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRole(AWSSecurityTokenServiceClient.java:498)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRole(AWSSecurityTokenServiceClient.java:467)
	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider.newSession(STSAssumeRoleSessionCredentialsProvider.java:348)
	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider.access$000(STSAssumeRoleSessionCredentialsProvider.java:44)
	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider$1.call(STSAssumeRoleSessionCredentialsProvider.java:93)
	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider$1.call(STSAssumeRoleSessionCredentialsProvider.java:90)
	at com.amazonaws.auth.RefreshableTask.refreshValue(RefreshableTask.java:295)
	at com.amazonaws.auth.RefreshableTask.blockingRefresh(RefreshableTask.java:251)
	at com.amazonaws.auth.RefreshableTask.getValue(RefreshableTask.java:192)
	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider.getCredentials(STSAssumeRoleSessionCredentialsProvider.java:320)
	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider.getCredentials(STSAssumeRoleSessionCredentialsProvider.java:43)
	at com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceProvider.getCredentials(STSProfileCredentialsServiceProvider.java:71)
	at com.amazonaws.auth.WebIdentityTokenCredentialsProvider.getCredentials(WebIdentityTokenCredentialsProvider.java:76)
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1266)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:842)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:792)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
```

[log4j-active (4).txt](https://github.com/awspring/spring-cloud-aws/files/8662831/log4j-active.4.txt)

**Comment by maciejwalkowiak** [comment]
I am not sure if this is a bug on our side or misaligned AWS SDK versions. Have you tried setting the version for AWS SDK as docs describe: https://docs.awspring.io/spring-cloud-aws/docs/2.4.1/reference/html/index.html#amazon-sdk-dependency-version-management and then just add the dependency to `aws-java-sdk-sts` without specifying the version?

**Comment by DineshNO** [comment]
Hi @maciejwalkowiak 
Thanks for the quick response.

Will try this.

**Comment by DineshNO** [comment]
Hi @maciejwalkowiak 
i got the same error .added the changes i did below.

I am sorry if i have misunderstood or didn't add enough information.
aws-java-sdk-sts - should be used only when the app is deployed to EKS ?

My situation is i am building an executable jar and run that from Databricks as a scheduled job.
We have an InstanceProfile setup in databricks which doesn't have access to secrets.So i am trying to configure something by which it can assume a role which has access to secrets.So i chose aws-java-sdk-sts to do the same and pass the role info via Environment Variable.

Please let me know if its the correct approach and if not please guide which credentialsProvider must i choose .
thanks in advance.
`
        <aws-java-sdk.version>1.12.215</aws-java-sdk.version>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>${aws-java-sdk.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
            <version>${spring.cloud.secrets.manager.config.version}</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
        </dependency>

`

**Comment by maciejwalkowiak** [comment]
It does not seem to be an issue with Spring Cloud AWS but either with AWS SDK, or there is a missing configuration that i am not aware of.

Same issue with pure AWS SDK is reproduced here: https://github.com/maciej-scratches/aws-sts-infinite-loop

Related issue reported to AWS SDK: https://github.com/aws/aws-sdk-java/issues/2760

Closing it for now as seems there is nothing we can do about it, but will watch the issue reported in AWS SDK.

**Comment by DineshNO** [comment]
Hi @maciejwalkowiak ,
I am facing difficulty in setting up a logger for displaying aws related logs.
Attaching pom.xml and log42.xml to my application.
I am using lombok @Slf4j loggers which works for my classes but can't find the same for aws.
Please help configure the logs.

pom.xml

` <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
`

log4j2.xml

<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%style{%d{ISO8601}}{black} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%C{1.}}{bright,yellow}: %msg%n%throwable"/>
        </Console>

        <RollingFile name="RollingFile"
                     fileName="./logs/spring-boot-logger-log4j2.log"
                     filePattern="./logs/$${date:yyyy-MM}/spring-boot-logger-log4j2-%d{-dd-MMMM-yyyy}-%i.log.gz">
            <PatternLayout>
                <pattern>%d %p %C{1.} [%t] %m%n</pattern>
            </PatternLayout>
            <Policies>
                
                <OnStartupTriggeringPolicy/>
                <SizeBasedTriggeringPolicy
                        size="10 MB"/>
                <TimeBasedTriggeringPolicy/>
            </Policies>
        </RollingFile>
    </Appenders>

    <Loggers>
        <Root level="trace">
            <AppenderRef ref="Console"/>
            <AppenderRef ref="RollingFile"/>
        </Root>
    </Loggers>
</Configuration>

**Comment by maciejwalkowiak** [comment]
Perhaps they aren't easy to find when you have root set to `trace`. Try this config:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%style{%d{ISO8601}}{black} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%C}{bright,yellow}: %msg%n%throwable"/>
        </Console>
    </Appenders>

    <Loggers>
        <Root level="info">
            <AppenderRef ref="Console"/>
        </Root>
        <Logger name="com.amazonaws" level="trace" additivity="false">
            <AppenderRef ref="Console"/>
        </Logger>
    </Loggers>
</Configuration>
```

Find fully working example here: https://github.com/maciej-scratches/aws-sts-infinite-loop/tree/logging

**Comment by maciejwalkowiak** [comment]
Yes, if its not optional and its not able fetch secrets, application should fail to start
