### ISSUE TITLE
Unable to resolve SNS ARNs

### ISSUE THREAD

**Issue by PatrickGotthard** [awspring/spring-cloud-aws#588]
**Type**: Bug

**Component**: SNS

**Describe the bug**
After upgrading to 3.0.0-M3 I'm unable to send SNS Notifications due to broken resolution of SNS ARNs:
```
software.amazon.awssdk.services.sns.model.InvalidParameterException: Invalid parameter: Topic Name (Service: Sns, Status Code: 400, Request ID: fa3d86c8-c434-59fe-baf0-daddd9b97589)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.sns.DefaultSnsClient.createTopic(DefaultSnsClient.java:722)
	at io.awspring.cloud.sns.core.DefaultTopicArnResolver.resolveTopicArn(DefaultTopicArnResolver.java:49)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.awspring.cloud.sns.core.CachingTopicArnResolver.resolveTopicArn(CachingTopicArnResolver.java:43)
	at io.awspring.cloud.sns.core.SnsTemplate.resolveMessageChannelByTopicName(SnsTemplate.java:139)
	at io.awspring.cloud.sns.core.SnsTemplate.convertAndSend(SnsTemplate.java:105)
	at io.awspring.cloud.sns.core.SnsTemplate.convertAndSend(SnsTemplate.java:93)
```

I think that it's a permission problem because the application does not have permissions to create SNS Topics: https://github.com/awspring/spring-cloud-aws/blob/bb9992bb2440b4373bd7aac09265734278ae7826/spring-cloud-aws-sns/src/main/java/io/awspring/cloud/sns/core/DefaultTopicArnResolver.java#L49

**Sample**
```java
import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Component;

import io.awspring.cloud.sns.core.SnsHeaders;
import io.awspring.cloud.sns.core.SnsTemplate;
import lombok.AllArgsConstructor;

@Component
@AllArgsConstructor
public class SnsClient {

    private final SnsTemplate sns;

    public void send() {

        final String destination = "test.fifo";
        final String payload = "test";

        final Map<String, Object> headers = new HashMap<>();
        headers.put(SnsHeaders.MESSAGE_GROUP_ID_HEADER, "test");

        this.sns.convertAndSend(destination, payload, headers);

    }

}
```

**Comment by PatrickGotthard** [comment]
As a workaround I'm resolving the topics with the following code:
```java
    public String getArn(final String name) {

        // @formatter:off
        return this.snsClient.listTopicsPaginator().topics().stream()
            .map(Topic::topicArn)
            .filter(arn -> arn.contains(name))
            .findFirst()
            .orElseThrow(() -> new IllegalArgumentException("Unable to find topic: " + name));
        // @formatter:on

    }
```

As far as I can tell the AWS SDK does not return the name of the topic so this is a little bit hacky.

**Comment by maciejwalkowiak** [comment]
@MatejNedic perhaps you can take a look?

**Comment by MatejNedic** [comment]
Will take a look in following days!

**Comment by MatejNedic** [comment]
In 3.0 due to performance reasons, we decided to resolve the name by making a call to create a topic. This is done because the topic ARN is returned if the topic exists [check].(https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sns/SnsClient.html#createTopic(software.amazon.awssdk.services.sns.model.CreateTopicRequest))

If we did not do that we would have to list all topics and get their ARNS which can be expensive. We also cache the topic name to ARN.

If you would like to create your own resolvment of the topic name to ARN you will need to implement `TopicArnResolver` and register it as a Bean. Our autoconfiguration will pick it up and use it inside of `SNSTemplate`. If you need help I can provide you sample.

If you check [Docs](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-M3/reference/html/index.html#sns-template) creating of the topic is explained there as well.

**Comment by PatrickGotthard** [comment]
Hi @MatejNedic,

thanks for clarification, it's no problem to implement a custom TopicArnResolver for me. As commented above I've already implemented the "old" resolution myself.

But maybe you could consider to ship such a resolver for other users as well...?

Regards,
Patrick
