### ISSUE TITLE
Unable to load config data from 'aws-secretsmanager:'

### ISSUE THREAD

**Issue by mikelhamer** [awspring/spring-cloud-aws#590]
**Type**: Bug

**Component**: Secrets Manager

**Describe the bug**
Unable to load configuration as specified in the documentation here
https://docs.awspring.io/spring-cloud-aws/docs/current/reference/html/index.html#integrating-your-spring-cloud-application-with-the-aws-secrets-manager

When I start my application I get an error that says "Unable to load config data from 'aws-secretsmanager:'". The only thing I can find when I search for this issue is this [stackoverflow question](https://stackoverflow.com/questions/70375435/importing-secrets-in-spring-boot-application-from-aws-secrets-manager), but all that mentions is making sure the correct dependency is being used, which I am doing. See example project below.

**Sample**
https://github.com/mikelhamer/spring-cloud-bug

**Comment by maciejwalkowiak** [comment]
Can you paste full console output?

Also, can you verify if it works with 3.0.0-M3 or at least you get more self-explanatory error message?

**Comment by mikelhamer** [comment]
> Can you paste full console output?

```
java.lang.IllegalStateException: Unable to load config data from 'aws-secretsmanager:'
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:141) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:126) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.resolve(StandardConfigDataLocationResolver.java:119) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.lambda$resolve$1(ConfigDataLocationResolvers.java:115) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:126) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:115) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataLocationResolvers.resolve(ConfigDataLocationResolvers.java:107) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataImporter.resolve(ConfigDataImporter.java:105) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataImporter.resolve(ConfigDataImporter.java:97) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:85) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:116) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:240) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:227) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.24.jar:5.3.24]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66) ~[spring-boot-2.7.6.jar:2.7.6]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:343) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.6.jar:2.7.6]
	at com.example.springcloudbug.SpringCloudBugApplication.main(SpringCloudBugApplication.java:10) ~[classes/:na]
Caused by: java.lang.IllegalStateException: File extension is not known to any PropertySourceLoader. If the location is meant to reference a directory, it must end in '/' or File.separator
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferencesForFile(StandardConfigDataLocationResolver.java:229) ~[spring-boot-2.7.6.jar:2.7.6]
	at org.springframework.boot.context.config.StandardConfigDataLocationResolver.getReferences(StandardConfigDataLocationResolver.java:138) ~[spring-boot-2.7.6.jar:2.7.6]
	... 31 common frames omitted


Process finished with exit code 1
```


> Also, can you verify if it works with 3.0.0-M3 or at least you get more self-explanatory error message?

I've been trying, but keep running this error or other depending on how I try the dependencies. `org.springframework.cloud:spring-cloud-build:pom:4.0.0-M4 was not found in https://repo.maven.apache.org/maven2 ` do you have a sample project using 3.0.0-M that I could reference?

**Comment by MatejNedic** [comment]
Hey @mikelhamer ,
You are not providing names of your secrets inside AWS. 
For example, if you have a secret inside of AWS with the name `/prod/database/db-instance1 `
Inside Spring Cloud AWS you will need to have `spring.config.import:/prod/database/db-instance-1` -> (check [sample](https://github.com/awspring/spring-cloud-aws/tree/main/spring-cloud-aws-samples/spring-cloud-aws-secrets-manager-sample)
We are not providing automatic discovery and loading because of performance issues and cost this would inquire. 
This is why you have to specify exactly which keys you want to have loaded, which is also the right way to do configuration.

**Comment by mikelhamer** [comment]
> We are not providing automatic discovery and loading because of performance issues and cost this would inquire. This is why you have to specify exactly which keys you want to have loaded, which is also the right way to do configuration.

Hmm, this statement seems to conflict with this part of the docs. To be clear, I'm talking about version 2.4.
<img width="965" alt="image" src="https://user-images.githubusercontent.com/10012080/208290045-4ef2a306-6b33-4b06-8c87-768bc129d869.png">

**Comment by MatejNedic** [comment]
> > We are not providing automatic discovery and loading because of performance issues and cost this would inquire. This is why you have to specify exactly which keys you want to have loaded, which is also the right way to do configuration.
> 
> Hmm, this statement seems to conflict with this part of the docs. To be clear, I'm talking about version 2.4. <img alt="image" width="965" src="https://user-images.githubusercontent.com/10012080/208290045-4ef2a306-6b33-4b06-8c87-768bc129d869.png">

This is the main reason it was removed in 3.0.0. Let me check for version 2.4 and get back to you (thought you were talking about 3.0).

**Comment by MatejNedic** [comment]
@mikelhamer in your example you are using the wrong dependency.
Please try with:

```
 <dependency>
   <groupId>io.awspring.cloud</groupId>
    <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
 </dependency>
```

Instead of:

```
<dependency>
     <groupId>io.awspring.cloud</groupId>
      <artifactId>spring-cloud-aws-secrets-manager-config</artifactId>
</dependency>
```
I tried it locally works for me.

**Comment by mikelhamer** [comment]
> @mikelhamer in your example you are using the wrong dependency. Please try with:
> 
> ```
>  <dependency>
>    <groupId>io.awspring.cloud</groupId>
>     <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
>  </dependency>
> ```
> 
> Instead of:
> 
> ```
> <dependency>
>      <groupId>io.awspring.cloud</groupId>
>       <artifactId>spring-cloud-aws-secrets-manager-config</artifactId>
> </dependency>
> ```
> 
> I tried it locally works for me.

Woooowwwwwwwww, thank you! Silly mistake on my part. Thank you so much!!!
