### ISSUE TITLE
Advice on How to Configure Spring Boot DevTools

### ISSUE THREAD

**Issue by akefirad** [awspring/spring-cloud-aws#596]
**Type**: Bug

This is more of a documentation bug. Would you please advice on how to configure class loading of Spring Boot DevTools so that both DynamoDB and SecretsManager module can be used together. What I tried:
```properties
restart.include.dynamodb=/dynamodb-[-\\w\\d\.]+\.jar
restart.include.awspring=spring-cloud-aws-[-\\w\\d\.]+\.jar
```
But it's not enough. The class of `SecretsManagerConfigDataResource` doesn't get matched.
Let me know if you need a sample project.

**Comment by maciejwalkowiak** [comment]
What is exactly the issue? Yes, please provide a sample project.

**Comment by akefirad** [comment]
There you go: [demo.zip](https://github.com/awspring/spring-cloud-aws/files/10299625/demo.zip)
The objective is to get this project to start and successfully make a `POST /foos` call.
Right now, it fails to start with:
```
09:41:32.421 [restartedMain] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: No loader found for resource '[SecretsManagerConfigDataResource@55580fa context = '/my/foo/bar/secret', optional = false]'
	at org.springframework.util.Assert.state(Assert.java:97)
	at org.springframework.boot.context.config.ConfigDataLoaders.getLoader(ConfigDataLoaders.java:114)
	at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:93)
	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:128)
	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:86)
	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:115)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processWithProfiles(ConfigDataEnvironment.java:313)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:234)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:96)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:352)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
	at com.example.demo.DemoApplication.main(DemoApplication.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

Process finished with exit code 0
```
The issue is due to the way [DevTools](https://docs.spring.io/spring-boot/docs/3.0.0/reference/htmlsingle/#using.devtools) class loading logic works. If you remove (or disable) DevTools the startup issue is gone which proves the issue is indeed DevTools.
If you look at `spring-devtools.properties` file, you'd see some hack to make DevTools works with DynamoDB client. If you remove the two lines you can get secrets-manager functionality to work, but then DynamoDB client will stop working.
The more detailed explanation is that, since `ConfigDataLoaders` is in the _base_ class loader and and `SecretsManagerConfigDataResource` is not, (because it's _included_ manually in `spring-devtools.properties` file) the following code doesn't work anymore:
```java
private <R extends ConfigDataResource> ConfigDataLoader<R> getLoader(ConfigDataLoaderContext context, R resource) {
    ConfigDataLoader<R> result = null;
    for (int i = 0; i < this.loaders.size(); i++) {
        ConfigDataLoader<?> candidate = this.loaders.get(i);
        if (this.resourceTypes.get(i).isInstance(resource)) { // <- This never evaluates to true
            // ...
        }
    }
    // ...
}
```
If you debug the above, you'd see that the check is checking two classes with the same name but different class loaders (which is expected).

**Comment by maciejwalkowiak** [comment]
Current status of investigation:

The issue is not so much with the Spring Cloud AWS but with the DynamoDB enhanced client & Spring Boot Devtools compatibility. From what I can see so far, if you declare schemas manually with `StaticTableSchema` instead of using `TableSchema.fromClass(..)` your sample works fine. Looks like caching getter/setter method references refer to class loaded with a wrong class loader, but I am not sure yet what's the reason and how to fix it.

**Comment by maciejwalkowiak** [comment]
Unfortunately there is no way to get it running until the issue in AWS SDK is solved: https://github.com/aws/aws-sdk-java-v2/issues/2604

Moving DynamoDB jars to restart classloader is also not an option as then more jars would need to be moved which defeats the purpose. 

Also, I don't see a way to use `ConfigDataLoader` when loaders are moved to restart classloader. 

As a result - the current solution is to define schema manually - which anyway seems to be the right way to go - considering that generating schema from a bean does not work on GraalVM native image. I added PR to docs explaining what to do.
