### ISSUE TITLE
Issue with spring-cloud-aws-starter-sqs 3.0.0.M3 - Expected a profile or property definition on line 1

### ISSUE THREAD

**Issue by wllianwd** [awspring/spring-cloud-aws#623]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
While trying to migrate to the new SQS starter compatible with Spring Boot 3 I'm getting issues.

I tried to follow exactly the same as in the provided SQS sample: https://github.com/awspring/spring-cloud-aws/tree/main/spring-cloud-aws-samples/spring-cloud-aws-sqs-sample

My docker compose file:
```
version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: "sqs,sns"
      DEFAULT_REGION: "eu-west-1"
      HOSTNAME_EXTERNAL: "localhost"
      DEBUG: "1"
    ports:
      - "4566-4593:4566-4593"
      - "8082:8080"
```

My application.properties:
```
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.region.static=eu-west-1
spring.cloud.aws.credentials.access-key=noop
spring.cloud.aws.credentials.secret-key=noop
```

But I have the below issue:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqsSampleProducer' defined in file [../target/classes/com/test/sampleservice/SqsSampleProducer.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'sqsAsyncClient' defined in class path resource [io/awspring/cloud/autoconfigure/sqs/SqsAutoConfiguration.class]: Failed to instantiate [software.amazon.awssdk.services.sqs.SqsAsyncClient]: Factory method 'sqsAsyncClient' threw exception with message: Expected a profile or property definition on line 1
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-6.0.3.jar:6.0.3]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.3.jar:6.0.3]
        ...
```

**Sample**

I created the below sample to reproduce the issue:
https://github.com/wllianwd/sampleservice-sqs-issue

**Comment by maciejwalkowiak** [comment]
Your example works for me. Can you take a look if everything is ok with your `~/.aws/config` and `~/.aws/credentials` files? Cause the error looks suspiciously similar to https://github.com/aws/aws-toolkit-jetbrains/issues/1793

**Comment by wllianwd** [comment]
Hey @maciejwalkowiak, thanks for the feedback.

Why `~/.aws/config` and `~/.aws/credentials` would be used if I'm using localstack?

Before migrating to the `3.0.0-M3` version, for testing, we configured it like that:
```
@Configuration
class LocalAmazonConfig(
    @Value("\${localstack.sqs-host}") private val sqsHost: String,
    @Value("\${localstack.region}") private val region: String
) {

    @Primary
    @Bean
    fun amazonSqs(): AmazonSQSAsync {
        return AmazonSQSAsyncClientBuilder.standard()
            .withEndpointConfiguration(EndpointConfiguration(sqsHost, region))
            .build()
    }

    @Primary
    @Bean
    fun simpleMessageListenerContainerFactory(
        amazonSQSAsync: AmazonSQSAsync
    ): SimpleMessageListenerContainerFactory {
        val factory = SimpleMessageListenerContainerFactory()
        factory.setAmazonSqs(amazonSQSAsync)
        factory.setWaitTimeOut(1)
        return factory
    }

}
```

**Comment by wllianwd** [comment]
Ah ok, if the files are there, they are validated right?

I removed and reconfigured the files, now they are valid, looks ok now.

**Comment by maciejwalkowiak** [comment]
It seems that if you remove them it works well but if they are malformed AWS SDK complain. We don't touch any of them in Spring Cloud AWS.
