### ISSUE TITLE
Not able to send emails with AWS SES with Spring Boot 3.0.x

### ISSUE THREAD

**Issue by rjrb** [awspring/spring-cloud-aws#743]
**Type**:
Bug

**Component**:
SES

**Describe the bug**
I'm not able to send messages with HTML and/or attachments (MimeMessage) using the JavaMailSender and Spring Boot 3.0.x, and the recent migration to jakarta.mail (replacing the old javax.mail). I've tried multiple ways, but all fail with different messages. Everything works fine if I go back to Spring Boot 2.7.10 and version 1.0.15 of the dependency management.

**Sample**
I'm attaching a sample application that uses the AWS credentials file for authentication and tries to create and send the mime message in three different ways and all fail (all intents as part of `EmailApplication.java`). A plain email does go through. My AWS account has SES in production mode and is able to send emails from verified senders with no issues.

Plugins:
```gradle
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.0.5'
	id 'io.spring.dependency-management' version '1.1.0'
}
```

These are the dependencies I'm using:
```gradle
implementation 'org.springframework.boot:spring-boot-starter-mail'
implementation 'io.awspring.cloud:spring-cloud-starter-aws-ses:2.4.4'
implementation 'javax.mail:mailapi:1.4.3'
```
I've tried with `'com.sun.mail:javax.mail:1.6.2'` instead of `'javax.mail:mailapi:1.4.3'` or without any of them and it doesn't work either.

And this is how I'm creating the sender's beans:
```java
@Configuration
public class EmailConfig {

	@Bean
	public AmazonSimpleEmailService amazonSimpleEmailService() {
		return AmazonSimpleEmailServiceClientBuilder
			.standard()
			.withRegion(Regions.US_WEST_2)
			.build()
		;
	}

	@Bean
	public MailSender mailSender(AmazonSimpleEmailService amazonSimpleEmailService) {
		return new SimpleEmailServiceMailSender(amazonSimpleEmailService);
	}

	@Bean
	public JavaMailSender javaMailSender(AmazonSimpleEmailService amazonSimpleEmailService) {
		return new SimpleEmailServiceJavaMailSender(amazonSimpleEmailService);
	}

}
```

[email.zip](https://github.com/awspring/spring-cloud-aws/files/11107086/email.zip)

**Comment by maciejwalkowiak** [comment]
@rjrb Spring Cloud AWS 2.x is compatible with Spring Boot 2.x.

For Spring Boot 3.x you need Spring Cloud AWS 3.x (check https://github.com/awspring/spring-cloud-aws#compatibility-with-spring-project-versions).

Once you upgrade you should not hit any issues. Let me know if anything is still unclear.

**Comment by rjrb** [comment]
Hi @maciejwalkowiak, thanks for replying.

I made some adjustments according to your suggestions, but I still can't get it to work (plain email still works), so I guess something is missing.

I updated `build.gradle` with what I believe are the right dependencies for Spring Boot 3.0.x, I removed the `EmailConfig.java` to rely on the autoconfiguration, but I still get an exception related to the `Session`.

This is the new build.gradle:
```gradle
plugins {
	id 'java'
	id 'org.springframework.boot' version '3.0.5'
	id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.mail'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
}

ext {
  set('springCloudVersion', "3.0.0-RC1")
}

dependencyManagement {
  imports {
    mavenBom "io.awspring.cloud:spring-cloud-aws-dependencies:${springCloudVersion}"
  }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'io.awspring.cloud:spring-cloud-aws-starter-ses'
	implementation 'javax.mail:mailapi:1.4.3'
//	implementation 'com.sun.mail:javax.mail:1.6.2'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
```

And this is the error I get:

```
java.lang.NoSuchMethodError: 'void com.sun.mail.util.LineInputStream.<init>(java.io.InputStream, boolean)'
        at com.sun.mail.util.MailStreamProvider.inputLineStream(MailStreamProvider.java:73) ~[jakarta.mail-1.0.0.jar:na]
        at com.sun.mail.util.MailStreamProvider.inputLineStream(MailStreamProvider.java:28) ~[jakarta.mail-1.0.0.jar:na]
        at jakarta.mail.Session.loadProvidersFromStream(Session.java:1039) ~[jakarta.mail-1.0.0.jar:na]
        at jakarta.mail.Session.access$000(Session.java:201) ~[jakarta.mail-1.0.0.jar:na]
        at jakarta.mail.Session$2.load(Session.java:970) ~[jakarta.mail-1.0.0.jar:na]
        at jakarta.mail.Session.loadAllResources(Session.java:1232) ~[jakarta.mail-1.0.0.jar:na]
        at jakarta.mail.Session.loadProviders(Session.java:989) ~[jakarta.mail-1.0.0.jar:na]
        at jakarta.mail.Session.<init>(Session.java:269) ~[jakarta.mail-1.0.0.jar:na]
        at jakarta.mail.Session.getInstance(Session.java:323) ~[jakarta.mail-1.0.0.jar:na]
        at io.awspring.cloud.ses.SimpleEmailServiceJavaMailSender.getSession(SimpleEmailServiceJavaMailSender.java:112) ~[spring-cloud-aws-ses-3.0.0-RC1.jar:3.0.0-RC1]
        at io.awspring.cloud.ses.SimpleEmailServiceJavaMailSender.createMimeMessage(SimpleEmailServiceJavaMailSender.java:169) ~[spring-cloud-aws-ses-3.0.0-RC1.jar:3.0.0-RC1]
        at com.email.EmailService.sendMessageWithAttachment(EmailService.java:41) ~[main/:na]
        at com.email.EmailApplication.lambda$0(EmailApplication.java:34) ~[main/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-3.0.5.jar:3.0.5]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) ~[spring-boot-3.0.5.jar:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-3.0.5.jar:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar:3.0.5]
        at com.email.EmailApplication.main(EmailApplication.java:17) ~[main/:na]
```

Any specific suggestion to fix it is highly appreciated, especially as I'm working with Gradle, and everything in the docs it's with Maven.

I'm attaching the updated code.

Thanks.

[email.zip](https://github.com/awspring/spring-cloud-aws/files/11113791/email.zip)

**Comment by techadri** [comment]
Hi @rjrb, 
I was able to reproduce the error using your sample application.

The JavaMail API dependency you are using is relatively old (May 2010) and apparently not compatible. When replacing the dependency with the most recent jakarta version `implementation 'jakarta.mail:jakarta.mail-api:2.1.1'`, your example works as expected. The only other change I had to do was to remove the bean definition of the `JavaMailSender` from the `EmailConfig`class, as you are using the starter dependency `io.awspring.cloud:spring-cloud-aws-starter-ses` that already includes that bean. 

I hope this helps to solve your issue.

**Comment by maciejwalkowiak** [comment]
Big thanks @techadri! You're 100% correct.

**Comment by rjrb** [comment]
Thanks @techadri and @maciejwalkowiak.

I may suggest updating the docs as they instruct you to use the library I was trying; [Spring Cloud AWS - SES - Sending Attachments](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-RC1/reference/html/index.html#sending-attachments)

**Comment by maciejwalkowiak** [comment]
@rjrb thanks for catching this! Would you like to contribute a PR to docs? I created an issue #749

**Comment by arunkpatra** [comment]
In addition to the `jakarta.mail:jakarta.mail-api` dependency (which is just teh API), an implementation of teh Java Mail API must also be in the classpath, for example `org.eclipse.angus:jakarta.mail`. Since the Java Mail API is just an opt-in for Spring Cloud AWS SES, both of these dependencies must be explicitly supplied to handle MIME messages. 

@rjrb Your sample app worked without the implementation i.e `org.eclipse.angus:jakarta.mail` because the `org.springframework.boot:spring-boot-starter-mail` dependency that you had included pulled in `org.eclipse.angus:jakarta.mail` transitively.

@maciejwalkowiak I have updated the sample app as well (apart from the docs) and added detail notes in the sample app.
