### ISSUE TITLE
Number MessageAttribute data type for timestamp is incompatible with older versions of Spring Cloud

### ISSUE THREAD

**Issue by angeloarenas** [awspring/spring-cloud-aws#791]
**Type**: Bug

**Component**:
SNS

**Describe the bug**
Upon upgrading a bunch of our services from the older `(org.springframework.cloud) Spring Cloud 2020.0.4` to the newer `(io.awspring.cloud) Spring Cloud 3.0.0-RC2`, when the **publisher is updated first**, the message attribute  type `Number` being set for the `timestamp` field is not supported in the **consumer running the older version of Spring Cloud.**

Upon listening to the message, the consumer is throwing
```
Exception in thread "simpleMessageListenerContainer-5" java.lang.StringIndexOutOfBoundsException: String index out of range: -1   
  at java.base/java.lang.Thread.run(Thread.java:829)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$SignalExecutingRunnable.run(SimpleMessageListenerContainer.java:310)
  at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$MessageExecutor.run(SimpleMessageListenerContainer.java:416)
  at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer$MessageExecutor.getMessageForExecution(SimpleMessageListenerContainer.java:464)
  at org.springframework.cloud.aws.messaging.core.QueueMessageUtils.createMessage(QueueMessageUtils.java:62)
  at org.springframework.cloud.aws.messaging.core.QueueMessageUtils.getMessageAttributesAsMessageHeaders(QueueMessageUtils.java:100)
  at org.springframework.cloud.aws.messaging.core.QueueMessageUtils.getNumberValue(QueueMessageUtils.java:117)
  at java.base/java.lang.String.substring(String.java:1841)
```

[This is where the message attribute type is set](https://github.com/awspring/spring-cloud-aws/blob/1b93b50c593d9485e0404d5088304a8d18dc5a43/spring-cloud-aws-sns/src/main/java/io/awspring/cloud/sns/core/TopicMessageChannel.java#L179)

Do you think it would be correct to set the message attribute type to `Number.<java class>` instead, similar to other number message headers [like this one](https://github.com/awspring/spring-cloud-aws/blob/1b93b50c593d9485e0404d5088304a8d18dc5a43/spring-cloud-aws-sns/src/main/java/io/awspring/cloud/sns/core/TopicMessageChannel.java#L174)?

This has been [fixed on the consumer side in this issue](https://github.com/spring-attic/spring-cloud-aws/issues/374) before, however, there is just no backwards compatibility when upgrading our producers to 3.0.0-RC2 while the consumers are in the meantime left at the older ~2020.0.4 version

**Sample**
Consumer with dependency
```
<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2020.0.4</version>
                <type>pom</type>
                <scope>import</scope>
</dependency>
```

Producer with dependency
```
<dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>3.0.0-RC2</version>
                <type>pom</type>
                <scope>import</scope>
</dependency>
```

Publish a message using 
```
snsTemplate.sendNotification("sns-topic-name", "some message string", null)
```
`timestamp` message attribute is automatically generated by Spring.
 
Consumer listens via SQS subscribed to `sns-topic-name`

The listener throws the exception described above.

**Comment by maciejwalkowiak** [comment]
@tomazfernandes can you take a look?

**Comment by tomazfernandes** [comment]
Hey @angeloarenas, sorry, this got out of my radar. We've done some improvements in this area - did you manage to get it working?

Thanks.

**Comment by Adita9** [comment]
Hello! 

I have the same issue as @angeloarenas . My publisher was upgraded to spring-cloud-aws-starter-sns 3.0.2 and my consumer is on spring-cloud-starter-aws-messaging 2.6.6 RELEASE.

Message attribute:
attributeName: timestamp
attributeType: number
attributeValue: 1698230823215

The application throws a StringIndexOutOfBoundsException when it tried to parse the attributeType in line 90 - org.springframework.cloud.aws.messaging.support.converter.NotificationRequestConverter#getNumberValue. (spring-cloud-starter-aws-messaging 2.6.6 RELEASE),

Do you know any workarounds?

Thank you!

**Comment by micMalloc** [comment]
@maciejwalkowiak 
Hello!
Can I ask when 3.0.3 version will be released?

**Comment by maciejwalkowiak** [comment]
Hopefully soon, in upcoming days, but we have some issues with builds on Github so can't give a date yet.
