### ISSUE TITLE
Why uisin UUID type for ID message header?

### ISSUE THREAD

**Issue by ivanfomkin** [awspring/spring-cloud-aws#814]
**Type**: Bug

**Component**:
"SQS"

**Describe the bug**
I'm try to work with yandex cloud with spring-cloud-aws 3.0.1 and I'm get error when I'm send and receive messages from Yandex Message Queue:
`java.lang.IllegalArgumentException: Invalid UUID string: 92898073-7bd6a160-5797b060-54a7e539` (any random String)
For receiving message root cause is:
```
java.lang.IllegalArgumentException: Invalid UUID string: 92898073-7bd6a160-5797b060-54a7e539
	at java.base/java.util.UUID.fromString1(UUID.java:280) ~[na:na]
	at java.base/java.util.UUID.fromString(UUID.java:258) ~[na:na]
	at io.awspring.cloud.sqs.support.converter.SqsHeaderMapper.toHeaders(SqsHeaderMapper.java:156) ~[spring-cloud-aws-sqs-3.0.1.jar:3.0.1]
	at io.awspring.cloud.sqs.support.converter.SqsHeaderMapper.toHeaders(SqsHeaderMapper.java:57) ~[spring-cloud-aws-sqs-3.0.1.jar:3.0.1]
```

When I'm try to send message to my queue I'm gett this root stacktrace (but messages success posting to queue)

```
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: cbc2063e-e13308bd-4ff0b3a3-b36398c6
	at java.base/java.util.UUID.fromString1(UUID.java:280) ~[na:na]
	at java.base/java.util.UUID.fromString(UUID.java:258) ~[na:na]
	at io.awspring.cloud.sqs.operations.SqsTemplate.lambda$doSendAsync$3(SqsTemplate.java:285) ~[spring-cloud-aws-sqs-3.0.1.jar:3.0.1]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[na:na]
```

In AWS docs I found description of MessageId field:
```
A unique identifier for the message. A MessageIdis considered unique across all AWS accounts for an extended period of time.

Type: String
```
It's placed here: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_Message.html

May be should not use UUID-type and just use String?

**Comment by tomazfernandes** [comment]
Hi @ivanfomkin, thanks for bringing this up.

The idea is that throughout the lifecycle of a message in the framework you can always assume the `Message`'s id is the same as what you received when you sent and / or received the message, including any internal logging you enable in the framework. Given Spring Messaging `Message` expects a UUID and AWS generates one, that's what the framework converts it to.

But considering we're restricting AWS's API contract, it might be better to reconsider that. Though it doesn't look like a trivial change from the receiving side.

I'll give it some thought. If anyone has an idea please let me know.

**Comment by tomazfernandes** [comment]
Hey @ivanfomkin.

I think from the feature perspective this shouldn't be too hard, in the sense that we can have some toggle in `SqsHeaderMapper` to add AWS's id as either the Spring `Message` UUID or add it as a separate header, both for sending and receiving messages.

The tricky part though is that there are parts of the code that rely on the `messageId` being in the Spring `Message` ID.

One part that comes to mind is in the `SqsTemplate` when receiving messages - it uses the message id to correlate with the `BatchDeletionResult.Entry`. So that logic would have to be changed to look for probably the separate Header, and if not found use the `Message` id.

So we'd need to take an overall look to see if there's anywhere else where we could run into problems with this change.

But overall, given we do have a good test coverage on that and the feature would be opt-in, I'd be inclined to give it a shot and see how it goes and if any other tests break with this change.

How do you feel about that? Would you be willing to contribute a PR for this?

Thanks.

**Comment by luanrjjj** [comment]
I would like try this issue. This this issue seems to be a good opportunity to learn the code and tests.

**Comment by tomazfernandes** [comment]
Hey @luanrjjj, sure, give it a shot. Let me know if you have any questions. Thanks.

**Comment by jm0514** [comment]
Hi @tomazfernandes,
I've reviewed this issue and would like to work on a fix for it. I'll follow the suggestions discussed above. 
Could you please assign this to me?

**Comment by injae-kim** [comment]
Fix PR: https://github.com/awspring/spring-cloud-aws/pull/1433 👍

**Comment by vicmosin** [comment]
Any updates here? Where can we expect the fix being released? Thank you

**Comment by maciejwalkowiak** [comment]
@vicmosin not sure if this won't require a breaking change, so can't tell any dates yet

**Comment by Sarkhad** [comment]
if the team is not going to merge the fix, is there any workaround available? 

I don't feel inspired to reinvent the wheel with own @SqsListener implementation just because of the type cast failing in one place.

**Comment by tomazfernandes** [comment]
Hi @Sarkhad,

The existing PR has been stale for a while and would need a few adjustments, so the fastest path forward would be a fresh PR scoped just to header mapping and correlation.

Target behavior:
	•	**Backward compatible by default:** if the provider MessageId is UUID-shaped, MessageHeaders.ID stays that same UUID.
	•	**Opt-in support for non-UUID ids:** add a Boot property and on `SqsHeaderMapper` that, when enabled, derives a deterministic UUID (UUID.nameUUIDFromBytes) for MessageHeaders.ID and exposes the raw provider id in a dedicated header.
	•	**Fail fast when not enabled:** if a non-UUID id is seen with the flag disabled, throw a clear error pointing to the property and the raw-id header.
	•	**Correlation uses provider id:** ack and send-result correlation use the provider MessageId (string), exposed via a dedicated header. For AWS this is the same value as MessageHeaders.ID today, so behavior is unchanged.
	•	**Send side parity:** SqsTemplate.doSendAsync() and doSendBatchAsync() handle non-UUID ids in send responses the same way.
	•	**Tests** + **documentation** covering both modes.

Implementation-wise, the main ask is a single, obvious way to access the raw provider id (for example via `MessagingMessageHeaders` and `MessageHeaderUtils` delegating to it), so we do not end up duplicating header lookup logic across call sites.

If you’re up for it, could you open a PR with this scope?

@maciejwalkowiak, feel free to chime in if you have anything to add.

**Comment by jm0514** [comment]
Hi @tomazfernandes,

Thank you for providing such a clear and specific direction for this fix. I already have an open PR (#1433) that addresses this issue.

Would it be okay if I update my existing PR to incorporate the approach you've outlined here, rather than opening a new one?

**Comment by tomazfernandes** [comment]
@jm0514, sure, go ahead. Let me know when it's ready for review. Thanks.
