### ISSUE TITLE
SQS doesn't consume notification messages from SNS

### ISSUE THREAD

**Issue by VelDeveloper** [awspring/spring-cloud-aws#829]
**Type**: Bug
I am using spring-boot 3.0.6, spring-cloud-aws: 3.0.1. I am publishing a message from SNS and based on filterType it will publish a message to the corresponding queue.

Message from SNS is publishing and I see SNS publish 200 in local stack logs but the SQS doesn't consume the message. When I set the debugger in "AbstractSqsMessageSource" I see the message payload but it is not sending this message payload to the @SqsListener method.

**Component**:
"SNS", "SQS" 

Please find the below code for your reference,

```
	@Bean
	public SqsTemplate sqsTemplate(SqsAsyncClient sqsAsyncClient) {
		return SqsTemplate.builder()
				.sqsAsyncClient(sqsAsyncClient)
				.configure(options -> options
						.acknowledgementMode(TemplateAcknowledgementMode.MANUAL))
				.build();
	}
	
			ActivationEvent activationEvent = ActivationEvent.builder()
				.clientId(faker.number().digits(5))
				.opcoId(faker.options().option("DE", "ES", "GB"))
				.partnerId(faker.options().option("sample", "flix", "play"))
				.build();

		// Build the message attributes
		Map<String, MessageAttributeValue> messageAttributes = new HashMap<>();
		MessageAttributeValue contentTypeAttributeValue = MessageAttributeValue.builder()
				.dataType("String")
				.stringValue("application/json") // Set the desired content type
				.build();
		messageAttributes.put("contentType", contentTypeAttributeValue);
		try {
			PublishRequest publishRequest = PublishRequest.builder()
					.topicArn(pollingConfiguration.sns().topicArn())
					.subject("Send notifications")
					.message(objectMapper.writeValueAsString(activationEvent))
					.messageAttributes(messageAttributes)
					.build();
			PublishResponse publish = snsClient.publish(publishRequest);
			log.debug("PublishResponse response {}", publish);
		} catch (JsonProcessingException e) {
			throw new RuntimeException(e);
		}


@Component
@RequiredArgsConstructor
@Slf4j
public class ActivationConsumer {


	@SqsListener(value = "dev-sample-job-v1",  pollTimeoutSeconds = "20", messageVisibilitySeconds="60", maxMessagesPerPoll = "10")
	public void processActivationEvent(String message,
									   Acknowledgement acknowledgement) {
									   		log.debug("Incoming order payload {}", message);
									   		}
						}
```
						
						
But the message was never reached the "processActivationEvent" method but I see below information in logs,

> i.a.c.s.l.s.AbstractSqsMessageSource - Received 1 messages from queue http://localhost:4566/000000000000/dev-sample-job-v1

										
						
						
But I am not sure why it doesn't reach that method. Also, I see some stack traces but not sure if it is related to this issue, 

```
java.util.concurrent.CompletionException: io.awspring.cloud.sqs.listener.AsyncAdapterBlockingExecutionFailedException: Error executing action in BlockingMessageListenerAdapter
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at io.awspring.cloud.sqs.listener.pipeline.MessageListenerExecutionStage.process(MessageListenerExecutionStage.java:49)
	at io.awspring.cloud.sqs.listener.pipeline.MessageProcessingPipelineBuilder$ComposingMessagePipelineStage.lambda$process$0(MessageProcessingPipelineBuilder.java:80)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
	at io.awspring.cloud.sqs.listener.pipeline.MessageProcessingPipelineBuilder$ComposingMessagePipelineStage.process(MessageProcessingPipelineBuilder.java:80)
	at io.awspring.cloud.sqs.listener.pipeline.MessageProcessingPipelineBuilder$FutureComposingMessagePipelineStage.process(MessageProcessingPipelineBuilder.java:104)
	at io.awspring.cloud.sqs.listener.pipeline.MessageProcessingPipelineBuilder$FutureComposingMessagePipelineStage.process(MessageProcessingPipelineBuilder.java:104)
	at io.awspring.cloud.sqs.listener.pipeline.MessageProcessingPipelineBuilder$FutureComposingMessagePipelineStage.process(MessageProcessingPipelineBuilder.java:104)
	at io.awspring.cloud.sqs.listener.pipeline.MessageProcessingPipelineBuilder$FutureComposingMessagePipelineStage.process(MessageProcessingPipelineBuilder.java:104)
	at io.awspring.cloud.sqs.listener.sink.AbstractMessageProcessingPipelineSink.lambda$execute$0(AbstractMessageProcessingPipelineSink.java:99)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: 
```

Any help would be really appreciable. Also, it would be great if we update spring-cloud-aws-samples should have some advanced samples instead if basic one.

**Comment by tomazfernandes** [comment]
Hi @VelDeveloper, thanks for opening the issue.

This stack trace does seem to be related to your problem. Can you provide the full stack trace so we can take a look?

Thanks.

**Comment by tomazfernandes** [comment]
Hi @VelDeveloper, I think you are confusing `AcknowledgementMode` with `TemplateAcknowledgementMode`.

The first one applies to `MessageListenerContainers` such as the ones created by the `@SqsListener` annotation.

The second one applies to when you're using the `SqsTemplate` for receiving messages.

In order to use manual acknowledgement and receive an `Acknowledgement` object in the listener, you need to have the container acknowledgement set to `MANUAL`.

Does this answer your question?

Thanks.

**Comment by M-Jai-ganesh** [comment]
I am also facing same issue

**Comment by codingsince1985** [comment]
> Hi @VelDeveloper, I think you are confusing `AcknowledgementMode` with `TemplateAcknowledgementMode`.
> 
> The first one applies to `MessageListenerContainers` such as the ones created by the `@SqsListener` annotation.
> 
> The second one applies to when you're using the `SqsTemplate` for receiving messages.
> 
> In order to use manual acknowledgement and receive an `Acknowledgement` object in the listener, you need to have the container acknowledgement set to `MANUAL`.
> 
> Does this answer your question?
> 
> Thanks.

hi Tomaz, i'm aware of that this issue has been closed for a while.
however i couldn't find anything regarding using `SqsTemplate` to manually acknowledge a message when setting `TemplateAcknowledgementMode` to `MANUAL`.
and someone else is in the same boat, https://stackoverflow.com/questions/77892035/spring-sqstemplate-manual-acknowledgement-how-to
i'd appreciate if you could provide us with further information.
