### ISSUE TITLE
When manual SqsMessageListenerContainer do not shutdown in sample 

### ISSUE THREAD

**Issue by xyzlast** [awspring/spring-cloud-aws#840]
**Type**: Bug

**Component**: SQS

SqsMessageListenerContainer cannot finish in 20 seconds.

**Sample**

Here is my configuration

```java
@Slf4j
@Configuration
@EnableAsync(proxyTargetClass = true)
public class AdminMqConfig {
    @Bean
    public MessageListenerContainer<Object> manualPushMessageListenerContainer(SqsAsyncClient sqsAsyncClient) {
        return SqsMessageListenerContainer.builder()
            .sqsAsyncClient(sqsAsyncClient)
            .messageListener(System.out::println)
            .queueNames("sqsName.fifo")
            .id("id")
            .build();
    }
}

```

and show shutdown error in console

```
2023-06-22T194143.780 WARN  --- [ i.a.c.s.l.s.AbstractPollingMessageSource ] Tasks did not finish in 20 seconds for queue sqsName, proceeding with shutdown
2023-06-22T194143.780 ERROR --- [ i.a.c.s.l.s.AbstractPollingMessageSource ] Error polling for messages in queue 
java.util.concurrent.CancellationException: null
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2510)
	at io.awspring.cloud.sqs.listener.source.AbstractPollingMessageSource.lambda$stop$6(AbstractPollingMessageSource.java:305)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at io.awspring.cloud.sqs.listener.source.AbstractPollingMessageSource.stop(AbstractPollingMessageSource.java:305)
	at io.awspring.cloud.sqs.LifecycleHandler.lambda$manageLifecycle$4(LifecycleHandler.java:76)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1006)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at io.awspring.cloud.sqs.LifecycleHandler.manageLifecycle(LifecycleHandler.java:74)
	at io.awspring.cloud.sqs.LifecycleHandler.lambda$manageLifecycle$0(LifecycleHandler.java:81)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.lang.Thread.run(Thread.java:1589)
2023-06-22T194143.783 INFO  --- [ a.c.s.l.AbstractMessageListenerContainer ] Container sqsName stopped
```

**Comment by pushkar-r** [comment]
@xyzlast Did you find a solution for this? I am having the same issue and stuck on it since last 2 days.

**Comment by pushkar-r** [comment]
I've managed to fix this. Changed acknowledge(); to acknowledgeAsync();

https://github.com/awspring/spring-cloud-aws/issues/925
