### ISSUE TITLE
AWS SDK dependencies creating issue

### ISSUE THREAD

**Issue by ramyogi7283** [awspring/spring-cloud-aws#988]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
Using version 3.0.0

```
<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-crt-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-sqs</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>netty-nio-client</artifactId>
                    <groupId>software.amazon.awssdk</groupId>
                </exclusion>
            </exclusions>
        </dependency>
    <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <exclusions>
                <exclusion>
                        <artifactId>netty-nio-client</artifactId>
                        <groupId>software.amazon.awssdk</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```
Along with Spring 3.0.2

I wanted to use S3AsyncClient to use my own logic with AwsCrtAsyncHttpClient.Builder  Because of https://github.com/aws/aws-sdk-java-v2/issues/4169

**Sample**
But when I use as above , I started getting Error
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Multiple HTTP implementations were found on the classpath. To avoid non-deterministic loading implementations, please explicitly provide an HTTP client via the client builders, set the software.amazon.awssdk.http.async.service.impl system property with the FQCN of the HTTP service to use as the default, or remove all but one HTTP implementation from the classpath.  The multiple implementations found were: [software.amazon.awssdk.http.crt.AwsCrtSdkHttpService,software.amazon.awssdk.http.nio.netty.NettySdkAsyncHttpService]
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[sdk-core-2.20.55.jar:na]
	at software.amazon.awssdk.core.internal.http.loader.ClasspathSdkHttpServiceProvider.loadService(ClasspathSdkHttpServiceProvider.java:74) ~[sdk-core-2.20.55.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at software.amazon.awssdk.core.internal.http.loader.SdkHttpServiceProviderChain.loadService(SdkHttpServiceProviderChain.java:44) ~[sdk-core-2.20.55.jar:na]
	at software.amazon.awssdk.core.internal.http.loader.CachingSdkHttpServiceProvider.loadService(CachingSdkHttpServiceProvider.java:46) ~[sdk-core-2.20.55.jar:na]
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkAsyncHttpClientBuilder.buildWithDefaults(DefaultSdkAsyncHttpClientBuilder.java:41) ~[sdk-core-2.20.55.jar:na]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveAsyncHttpClient$10(SdkDefaultClientBuilder.java:366) ~[sdk-core-2.20.55.jar:na]
	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[na:na]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveAsyncHttpClient(SdkDefaultClientBuilder.java:366) ~[sdk-core-2.20.55.jar:na]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeAsyncConfiguration(SdkDefaultClientBuilder.java:305) ~[sdk-core-2.20.55.jar:na]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:212) ~[sdk-core-2.20.55.jar:na]
	at software.amazon.awssdk.services.sqs.DefaultSqsAsyncClientBuilder.buildClient(DefaultSqsAsyncClientBuilder.java:39) ~[sqs-2.20.55.jar:na]
	at software.amazon.awssdk.services.sqs.DefaultSqsAsyncClientBuilder.buildClient(DefaultSqsAsyncClientBuilder.java:27) ~[sqs-2.20.55.jar:na]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:150) ~[sdk-core-2.20.55.jar:na]
	at io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration.sqsAsyncClient(SqsAutoConfiguration.java:73) ~[spring-cloud-aws-autoconfigure-3.0.0.jar:3.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

```I am not sure how to resolve this as it is tightly coupled with io.awsspring.  Please provide what I am missing. As soon I remove aws-crt-client and include netty-nio-client it works fine.

**Comment by ramyogi7283** [comment]
Sorry. Please ignore this or delete this issue. it is a false. I need to clear up netty-nio-client dependencies if need to use aws-crt-client

**Comment by maciejwalkowiak** [comment]
No worries @ramyogi7283! Thanks for coming back with solution.
